---
title: "PS811 Portfolio"
author: "Lotem Bassan"
output:
  pdf_document:
    toc: yes
  html_document:
    code_folding: hide
    toc: yes
---
```{r setup, include=FALSE}
## Defaults for R chunks
knitr::opts_chunk$set(echo = TRUE, ## echo = TRUE means code will show
                      warning=FALSE, ## supress warnings and messages from R
                      message=FALSE,
                      fig.path='Figs/', ## where to save figures
                      fig.height = 3, ## default figure size (can differ in each chunk)
                      fig.width = 3)

## Add any R packages you require. 
## Here are some we will use in 811:
requires <- c("tidyverse", ## tidyverse includes dplyr and ggplot2
              "magrittr",
              "foreign",
              "readstata13",
              "here")

## Install any you don't have
to_install <- c(requires %in% rownames(installed.packages()) == FALSE)
install.packages(c(requires[to_install], "NA"), repos = "https://cloud.r-project.org/" )

## Load all required R packages
library(tidyverse)
library(ggplot2); theme_set(theme_minimal())
library(magrittr)
library(here)

#Upload dataset
CIRI <- read.csv("dataset/CIRI.csv", header = TRUE, stringsAsFactors = TRUE)
```


```{r missing values}
CIRI %<>% 
  mutate(KILL = ifelse(KILL %in% c(-999,-77,-66), NA, KILL)) %>%
  mutate(TORT = ifelse(TORT %in% c(-999,-77,-66), NA, TORT)) %>%
  mutate(SPEECH = ifelse(SPEECH %in% c(-999,-77,-66), NA, SPEECH))
```

```{r summary-stats}
d  <- CIRI 

d %<>% 
  group_by(CTRY)%>%  
  mutate(mean_KILL = mean(KILL, na.rm = T),
         mean_TORT = mean(TORT, na.rm = T),
         mean_SPEECH = mean(SPEECH, na.rm = T) )

glimpse(d)

d1 <- d %>% 
  select(CTRY, POLITY, mean_KILL, mean_TORT, mean_SPEECH) %>% 
  distinct() 

glimpse(d1)
```

The correlation between Polity score and freedom from speech violations is 
`r cor(d1$POLITY, d1$mean_SPEECH, use="complete.obs") `.
The correlation between Polity score and freedom from torture violations is 
`r cor(d1$POLITY, d1$mean_TORT, use="complete.obs") `
The correlation between Polity score and freedom from political killings is 
`r cor(d1$POLITY, d1$mean_KILL, use="complete.obs")`

```{r scatterplot-Torture-Speech, fig.width=8}
d1 %>%
  ggplot() + 
  aes(x = mean_SPEECH, 
      y = mean_TORT, 
      color = mean_KILL, 
      size = POLITY, 
      label = CTRY) + 
  geom_point(alpha = .3) + 
  geom_text(check_overlap = T, 
            size = 4)+
  labs(x = "Freedom of Speech",
       y = "Freedom from Torture",
       color = "Freedom from Political Killings")
```



